# Generated by Django 6.0.3 on 2026-05-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_coursemodule_lesson'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseModule',
            new_name='Module',
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(default='THEORY', max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('VOICE', 'Voice')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(),
        ),
    ]
