# Generated by Django 6.0.3 on 2026-05-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_coursemodule_module_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('course', 'Course'), ('text', 'Text Note'), ('video', 'YouTube Video')], max_length=20)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('width', models.FloatField(default=300)),
                ('height', models.FloatField(default=200)),
                ('z_index', models.IntegerField(default=1)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='myapp.group')),
            ],
        ),
    ]
